commands:
  m2-clear-customers:
    class: \Driver\Magento2\Transformations\ClearCustomers
  m2-clear-orders:
    class: \Driver\Magento2\Transformations\ClearOrders
  m2-clear-quotes:
    class: \Driver\Magento2\Transformations\ClearQuotes
  m2-clear-reports:
    class: \Driver\Magento2\Transformations\ClearReports
  m2-clear-common:
    class: \Driver\Magento2\Transformations\ClearCommon
  m2-clear-swiftotter:
    class: \Driver\Magento2\Transformations\ClearSwiftOtter